# Generated by Django 3.0.7 on 2021-09-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblstate',
            },
        ),
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=50)),
                ('stateid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tbl_state')),
            ],
            options={
                'db_table': 'tblcity',
            },
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tbl_city'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tbl_state'),
        ),
    ]
